notifications:
  irc:
    channels: "chat.freenode.net#firedrake"
    skip_join: true
    on_success: change
    on_failure: always
    template: "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} | %{build_url}"
language: python
python:
  - "2.7_with_system_site_packages"
env:
  global:
    - C_INCLUDE_PATH=/usr/lib/openmpi/include
    - PETSC_CONFIGURE_OPTIONS="--download-ctetgen --download-triangle --download-chaco"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - "sudo apt-get install -qq build-essential python-dev git-core mercurial \
    cmake cmake-curses-gui libmed1 gmsh python-pip libhdf5-openmpi-dev \
    libopenmpi-dev openmpi-bin libblas-dev liblapack-dev gfortran \
    triangle-bin"
  - pip install --upgrade pip
# Force installation of requirements IN THE ORDER WE SPECIFIED!  AAAARGH.
  - "xargs -l1 pip install --allow-external mpi4py --allow-unverified mpi4py \
       --allow-external petsc --allow-unverified petsc \
       --allow-external petsc4py  --allow-unverified petsc4py \
       < requirements-ext.txt"
  - "xargs -l1 pip install --allow-external mpi4py --allow-unverified mpi4py \
       --allow-external petsc --allow-unverified petsc \
       --allow-external petsc4py  --allow-unverified petsc4py \
       < requirements-git.txt"
install: "python setup.py develop"
# command to run tests
script:
  - "make lint"
  - "py.test test --backend=sequential -v --tb=native"
  - "py.test test --backend=openmp -v --tb=native"
